name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y googletest libgtest-dev build-essential gcovr

    - name: Compile & run unit tests
      run: |
        make test
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
        ./main

    - name: Build default (sigmoid)
      run: make
    - name: Run default (sigmoid)
      run: ./main

    - name: Build bent_identity
      run: make bent_identity
    - name: Run bent_identity
      run: ./main

    - name: Build leaky_relu
      run: make leaky_relu
    - name: Run leaky_relu
      run: ./main
